-- Tabla para comentarios del foro en Supabase
create table if not exists public.comentarios (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id),
  nombre text not null,
  mensaje text not null,
  created_at timestamptz not null default now()
);

alter table public.comentarios enable row level security;

drop policy if exists "Permite seleccionar comentarios a todos" on public.comentarios;
create policy "Permite seleccionar comentarios a todos"
  on public.comentarios
  for select
  using (true);

drop policy if exists "Permite insertar comentarios a usuarios autenticados" on public.comentarios;
create policy "Permite insertar comentarios a usuarios autenticados"
  on public.comentarios
  for insert
  with check (auth.role() = 'authenticated');

drop policy if exists "Permite actualizar comentarios propios" on public.comentarios;
create policy "Permite actualizar comentarios propios"
  on public.comentarios
  for update
  using (auth.role() = 'authenticated' and auth.uid() = user_id)
  with check (auth.role() = 'authenticated' and auth.uid() = user_id);

drop policy if exists "Permite borrar comentarios propios" on public.comentarios;
create policy "Permite borrar comentarios propios"
  on public.comentarios
  for delete
  using (auth.role() = 'authenticated' and auth.uid() = user_id);
